Tp-promocion-peliculas/Models/Film.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Tp_promocion_peliculas.Models
{
    public class Film
    {
        public int Id { get; set; }


        [Display(Name = "Nombre de pelicula")]
        [Required(ErrorMessage = "El campo es requerido")]
        public string Title { get; set; }


        [Display(Name = "Fecha de estreno")]
        [Required(ErrorMessage = "El campo es requerido")]
        public DateTime ReleaseDate { get; set; }


        [Display(Name = "Imagen de pelicula")]
        public string Photo { get; set; }


        [Display(Name = "Trailer(link)")]
        [Required(ErrorMessage = "El campo es requerido")]
        public string Trailer { get; set; }


        [Display(Name = "Descripción")]
        [Required(ErrorMessage = "El campo es requerido")]
        public string Summary { get; set; }


        [Display(Name = "Genero")]
        [Required(ErrorMessage = "El campo es requerido")]
        public int? GenderId { get; set; }
        public Gender Genders { get; set; }


        [Display(Name = "En cartelera")]
        public bool billboard { get; set; }

        
        public List<MovieActor> MovieActors { get; set; }

    }
}

Tp-promocion-peliculas/Controllers/FilmsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Tp_promocion_peliculas;
using Tp_promocion_peliculas.Models;
using Tp_promocion_peliculas.ViewModel;

namespace Tp_promocion_peliculas.Controllers
{
    public class FilmsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment env;

        public FilmsController(ApplicationDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            this.env = env;
        }

        // GET: Films
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Movies.Include(f => f.Genders);
            var viewModel = new MovieViewModel();
            viewModel.Films = await applicationDbContext.ToListAsync();
            return View(viewModel);
        }

        // GET: Films/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Movies
                .Include(f => f.Genders)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        // GET: Films/Create
        public IActionResult Create()
        {
            ViewData["GenderId"] = new SelectList(_context.Genders, "Id", "Description");
            return View();
        }

        // POST: Films/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,ReleaseDate,Photo,Trailer,Summary,GenderId,billboard")] Film film)
        {
            if (ModelState.IsValid)
            {
               var file = HttpContext.Request.Form.Files;
                if (file != null && file.Count > 0)
                {
                    var filePhoto = file[0];
                    var pathDestine = Path.Combine(env.WebRootPath, "images\\movies");

                    if (filePhoto.Length > 0)
                    {
                        var fileDestine = Guid.NewGuid().ToString().Replace("-", "") + Path.GetExtension(filePhoto.FileName);

                        using (var filestream = new FileStream(Path.Combine(pathDestine, fileDestine), FileMode.Create))
                        {
                            filePhoto.CopyTo(filestream);
                            film.Photo = fileDestine;
                        };

                    }
                }

                _context.Add(film);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GenderId"] = new SelectList(_context.Genders, "Id", "Description", film.GenderId);
            return View(film);
        }

        // GET: Films/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Movies.FindAsync(id);
            if (film == null)
            {
                return NotFound();
            }
            ViewData["GenderId"] = new SelectList(_context.Genders, "Id", "Description", film.GenderId);
            return View(film);
        }

        // POST: Films/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,ReleaseDate,Photo,Trailer,Summary,GenderId,billboard")] Film film)
        {
            if (id != film.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var file = HttpContext.Request.Form.Files;
                if (file != null && file.Count > 0)
                {
                    var filePhoto = file[0];
                    var pathDestine = Path.Combine(env.WebRootPath, "images\\movies");

                    if (filePhoto.Length > 0)
                    {
                        var fileDestine = Guid.NewGuid().ToString().Replace("-", "") + Path.GetExtension(filePhoto.FileName);

                        using (var filestream = new FileStream(Path.Combine(pathDestine, fileDestine), FileMode.Create))
                        {
                            filePhoto.CopyTo(filestream);

                            string oldFile = Path.Combine(pathDestine, film.Photo);
                            if (System.IO.File.Exists(oldFile))
                                System.IO.File.Delete(oldFile);
                            film.Photo = fileDestine;
                        }

                    }
                }

                try
                {
                    _context.Update(film);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmExists(film.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GenderId"] = new SelectList(_context.Genders, "Id", "Description", film.GenderId);
            return View(film);
        }

        // GET: Films/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Movies
                .Include(f => f.Genders)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        // POST: Films/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var film = await _context.Movies.FindAsync(id);
            _context.Movies.Remove(film);

            //try
            //{
            //    await _context.SaveChangesAsync();
            //}
            //catch (Exception e)
            //{

            //    return this.Problem("No se puede eliminar esta pelicula");
            //}

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool FilmExists(int id)
        {
            return _context.Movies.Any(e => e.Id == id);
        }
    }
}

Tp-promocion-peliculas/Views/Films/Create.cshtml
@model Tp_promocion_peliculas.Models.Film

@{
    ViewData["Title"] = "Crear - pelicula";
}

<h1>Crear pelicula</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data" asp-controller="Films" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Photo" />
            <label>Imagen de pelicula</label>
            <div class="form-group">
                <img id="image" src="" alt="Imagen de pelicula" width="200" height="250" />
                <input asp-for="Photo" type="file" id="SelectedImg" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Trailer" class="control-label"></label>
                <input asp-for="Trailer" class="form-control" />
                <span asp-validation-for="Trailer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Summary" class="control-label"></label>
                <br />
                <textarea asp-for="Summary" rows="4" maxlength="200" minlength="1"></textarea>
                <span asp-validation-for="Summary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GenderId" class="control-label"></label>
                <select asp-for="GenderId" class="form-control" asp-items="ViewBag.GenderId"></select>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="billboard" /> @Html.DisplayNameFor(model => model.billboard)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="~/js//images.js"></script>

Tp-promocion-peliculas/Views/Films/Delete.cshtml
@model Tp_promocion_peliculas.Models.Film

@{
    ViewData["Title"] = "Borrar - pelicula";
}

<h1>Borrar pelicula</h1>

<h3>¿Estás seguro de que quiere borrar esto?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class="col-sm-2">
            <img src="~/images/Movies/@Model.Photo" alt="Imagen de pelicula" width="200" height="250" asp-append-version="true" />
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Photo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Trailer)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Trailer)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Summary)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Summary)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Genders)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Genders.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.billboard)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.billboard)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Borrar" class="btn btn-danger" /> |
        <a asp-action="Index">Regresar a la lista</a>
    </form>
</div>

Tp-promocion-peliculas/Views/Films/Details.cshtml
@model Tp_promocion_peliculas.Models.Film

@{ ViewData["Title"] = Html.DisplayFor(model => model.Title); }

<h1>@Html.DisplayFor(model => model.Title)</h1>

<div>
    <p>Fecha de estreno:</p>
    <span>@Html.DisplayFor(model => model.ReleaseDate)</span>
    <hr />

    <div class="row">
        <div class="col-md-12">
            <div class="row">
 
                <img src="~/images/movies/@Model.Photo" alt="Imagen de pelicula" width="250" height="300" asp-append-version="true" />
                <iframe src="@Html.DisplayFor(model => model.Trailer)" width="700" height="300"></iframe>
            </div>
            <div class="row">
                <div class="text-body">
                    <h6>Género: </h6>
                    <p>@Html.DisplayFor(model => model.Genders.Description)</p>
                </div>
            </div>
            <div class="row">
                <div class="text-body">
                    <h6>Descripción: </h6>
                    <p>@Html.DisplayFor(model => model.Summary)</p>
                </div>
            </div>
        </div>
    </div>
    @if (Model.MovieActors == null || Model.MovieActors.Count == 0)
     {
        <div>No hay actores en la pelicula</div>
        
     }
     else
     {
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Foto actor</th>
                        <th>Nombre actor</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.MovieActors)
                     {
                         <tr>
                            <td>
                             <img src="~/images/actors/@item.Person.Photo" height="90" width="90" asp-append-version="true" />
                            </td>
                            <td>
                               @Html.DisplayFor(modelItem => item.Person.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Film.Title)
                            </td>
                         </tr>                }
                </tbody>
            </table>
     }
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
    <a asp-action="Index">Regresar</a>
</div>

Tp-promocion-peliculas/Views/Films/Edit.cshtml
@model Tp_promocion_peliculas.Models.Film

@{
    ViewData["Title"] = "Editar - pelicula";
}

<h1>Editar pelicula</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data" asp-controller="Films" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Photo" class="control-label"></label>

                <span asp-validation-for="Photo" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Photo" />
            <div class="form-group">
                <img src="~/images/movies/@Model.Photo" id="image" asp-append-version="true" alt="Imagen de pelicula" width="200" height="250" />
                <input asp-for="Photo" type="file" id="SelectedImg" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Summary" class="control-label"></label>
                <br />
                <textarea asp-for="Summary"  rows="4" maxlength="200" minlength="1"></textarea>
                <span asp-validation-for="Summary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GenderId" class="control-label"></label>
                <select asp-for="GenderId" class="form-control" asp-items="ViewBag.GenderId"></select>
                <span asp-validation-for="GenderId" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="billboard" /> @Html.DisplayNameFor(model => model.billboard)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="~/js//images.js"></script>

Tp-promocion-peliculas/Views/Films/Index.cshtml
@model Tp_promocion_peliculas.ViewModel.MovieViewModel

@{
    ViewData["Title"] = "Peliculas";
}

<h1>Todas las peliculas</h1>

<p>
    <a class="btn btn-info" asp-action="Create">Crear nueva pelicula</a>
</p>


<h2>Cartelera semanal</h2>
<br />

<div class="row">
    @foreach (var item in Model.Films)
     {
        <div class="text-center">
            @if (item.billboard == true)
             {
                <div class="col-sm-3">
                    <div class="card text-white border-success bg-dark rounded" style="width: 15rem">
                        <a asp-action="Details" asp-route-id="@item.Id">
                            <img src="~/images/movies/@item.Photo" height="260" width="207" asp-append-version="true" alt=@Html.DisplayFor(modelItem => item.Title) />
                        </a>
                        <div class="card-body">
                            <h5 class="card-title">@Html.DisplayFor(modelItem => item.Title)</h5>
                            <div class="">
                                <a class="btn btn-info" asp-action="Edit" asp-route-id="@item.Id">Editar</a>
                                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Borrar</a>
                            </div>
                        </div>
                    </div>
                </div>
             }
        </div>
     }
</div>
<br />
<h2>Próximas extrenos de la semana siguiente</h2>
<br />
<div class="row">
    @foreach (var item in Model.Films)
     {
        <div class="text-center">
            @if (item.billboard == false)
             {
                <div class="col-sm-3">
                    <div class="card text-white border-danger bg-dark rounded" style="width: 15rem">
                        <a asp-action="Details" asp-route-id="@item.Id">
                            <img src="~/images/movies/@item.Photo" height="260" width="207" asp-append-version="true" alt=@Html.DisplayFor(modelItem => item.Title) />
                        </a>
                        <div class="card-body">
                            <h5 class="card-title">@Html.DisplayFor(modelItem => item.Title)</h5>
                            <div class="">
                                <a class="btn btn-info" asp-action="Edit" asp-route-id="@item.Id">Editar</a>
                                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Borrar</a>
                            </div>
                        </div>
                    </div>
                </div>
             }
        </div>
     }
</div>
<br />